# Import additional configuration files
import = [
  "~/.config/alacritty/themes/nord.toml",
  "~/.config/alacritty/fonts/CaskaydiaMono.toml",
]

shell = { program = "/usr/bin/tmux", args = ["new-session"] }

[window]
padding = { x = 5, y = 5 } # Default: x = 0, y = 0
dynamic_padding = true     # Default: false
decorations = "buttonless" # Default: "Full"
opacity = 0.95             # Default: 1.0

[scrolling]
history = 100_000 # Default: 10000

[font]
size = 10                 # Default: 11.25
offset = { x = 0, y = 1 } # Default: x = 0, y = 0

[terminal]
# Controls the OSC 52 behavior for clipboard interactions
osc52 = "CopyPaste" # Default: "OnlyCopy"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
