# https://alacritty.org/config-alacritty.html

###########
# GENERAL #
###########

# Import additional configuration files
import = []

# Shell program and its arguments
shell = {program = "/usr/bin/fish", args = ["--login"]}

# Working directory
working_directory = "None"  # Default: "None"

# Live config reload (changes require restart)
live_config_reload = true  # Default: true

# Offer IPC using alacritty msg (unix only)
ipc_socket = true  # Default: true

#######
# ENV #
#######

[env]
# Environment variables

##########
# WINDOW #
##########

[window]
# Window dimensions
dimensions = { columns = 0, lines = 0 }  # Default: columns = 0, lines = 0

# Window startup position
position = "None"  # Default: "None"

# Padding
padding = { x = 5, y = 5 }  # Default: x = 0, y = 0

# Dynamic padding
dynamic_padding = true  # Default: false

# Window decorations
decorations = "buttonless"  # Default: "Full"

# Opacity
opacity = 0.95  # Default: 1.0

# Blur (macOS/KDE Wayland only)
blur = false  # Default: false

# Startup mode
startup_mode = "SimpleFullscreen"  # Default: "Windowed"

# Window title
title = "Alacritty"  # Default: "Alacritty"

# Dynamic title
dynamic_title = true  # Default: true

# Window class (Linux/BSD only)
class = { instance = "Alacritty", general = "Alacritty" }  # Default: instance = "Alacritty", general = "Alacritty"

# Decorations theme variant
decorations_theme_variant = "None"  # Default: "None"

# Resize increments
resize_increments = false  # Default: false

# Option as Alt (macOS only)
option_as_alt = "None"  # Default: "None"

#############
# SCROLLING #
#############

[scrolling]

# Maximum number of lines in the scrollback buffer
history = 100_000  # Default: 10000

# Number of lines scrolled for every input scroll increment
multiplier = 3  # Default: 3

########
# FONT #
########

[font]

# Normal font style
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular

# Bold font style
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold

# Italic font style
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic

# Bold Italic font style
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic

# Font size in points
size = 11 # Default: 11.25

# Offset is extra space around each character
offset = { x = 0, y = 1 }  # Default: x = 0, y = 0

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Use built-in font for box drawing characters
builtin_box_drawing = true  # Default: true

##########
# COLORS #
##########

[colors]

# Transparent background colors
transparent_background_colors = false  # Default

# Draw bold text with bright colors
draw_bold_text_with_bright_colors = false  # Default

# Primary colors
[colors.primary]
foreground = "#d8d8d8"  # Default
background = "#181818"  # Default
dim_foreground = "#828482"  # Default
bright_foreground = "None"  # Default

# Cursor colors
[colors.cursor]
text = "CellBackground"  # Default
cursor = "CellForeground"  # Default

# Vi mode cursor colors
[colors.vi_mode_cursor]
text = "CellBackground"  # Default
cursor = "CellForeground"  # Default

# Search colors
[colors.search.matches]
foreground = "#181818"  # Default
background = "#ac4242"  # Default

[colors.search.focused_match]
foreground = "#181818"  # Default
background = "#f4bf75"  # Default

# Hint colors
[colors.hints.start]
foreground = "#181818"  # Default
background = "#f4bf75"  # Default

[colors.hints.end]
foreground = "#181818"  # Default
background = "#ac4242"  # Default

# Line indicator colors
[colors.line_indicator]
foreground = "None"  # Default
background = "None"  # Default

# Footer bar colors
[colors.footer_bar]
foreground = "#181818"  # Default
background = "#d8d8d8"  # Default

# Selection colors
[colors.selection]
text = "CellBackground"  # Default
background = "CellForeground"  # Default
# background = "#70c0b1"

# Normal colors
[colors.normal]
black = "#181818"  # Default
red = "#ac4242"  # Default
# green = "#90a959"  # Default
green = "#79c266"
yellow = "#f4bf75"  # Default
blue = "#6a9fb5"  # Default
magenta = "#aa759f"  # Default
cyan = "#75b5aa"  # Default
white = "#d8d8d8"  # Default

# Bright colors
[colors.bright]
black = "#6b6b6b"  # Default
red = "#c55555"  # Default
green = "#aac474"  # Default
yellow = "#feca88"  # Default
blue = "#82b8c8"  # Default
magenta = "#c28cb8"  # Default
cyan = "#93d3c3"  # Default
white = "#f8f8f8"  # Default

# Dim colors
[colors.dim]
black = "#0f0f0f"  # Default
red = "#712b2b"  # Default
green = "#5f6f3a"  # Default
yellow = "#a17e4d"  # Default
blue = "#456877"  # Default
magenta = "#704d68"  # Default
cyan = "#4d7770"  # Default
white = "#8e8e8e"  # Default

########
# BELL #
########

[bell]

# Visual bell animation effect
animation = "Linear"  # Default: "Linear"

# Duration of the visual bell flash in milliseconds
duration = 0  # Default: 0

# Visual bell animation color
color = "#ffffff"  # Default: "#ffffff"

# Command executed when the bell is rung
command = "None"  # Default: "None"

#############
# SELECTION #
#############

[selection]

# Characters that are used as separators for "semantic words" in Alacritty
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"  # Default: ",│`|:\"' ()[]{}<>\\t"

# When set to true, selected text will be copied to the primary clipboard
save_to_clipboard = true  # Default: false

##########
# CURSOR #
##########

[cursor]

# Cursor style
style = { shape = "Block", blinking = "On" }  # Default: shape = "Block", blinking = "Off"

# Vi mode cursor style (falls back to the active value of the normal cursor if "None")
vi_mode_style = "None"  # Default: "None"

# Cursor blinking interval in milliseconds
blink_interval = 750  # Default: 750

# Time after which cursor stops blinking, in seconds
blink_timeout = 0  # Default: 5

# When true, the cursor will be rendered as a hollow box when the window is not focused
unfocused_hollow = true  # Default: true

# Thickness of the cursor relative to the cell width
thickness = 0.15  # Default: 0.15

############
# TERMINAL #
############

[terminal]

# Controls the OSC 52 behavior for clipboard interactions
osc52 = "CopyPaste"  # Default: "OnlyCopy"

#########
# MOUSE #
#########

[mouse]

# When true, the cursor is temporarily hidden when typing
hide_when_typing = true  # Default: false

# Mouse bindings (actual bindings need to be defined as per user preference)
# Example: bindings = [{ mouse = "Left", action = "Paste" }]
bindings = []

#########
# HINTS #
#########

[hints]

# Define the keys used for hint labels
alphabet = "jfkdls;ahgurieowpq"  # Default: "jfkdls;ahgurieowpq"

# Enable specific hints
#[[hints.enabled]]
# Example configuration (actual settings to be defined based on user preference)
# regex = "..."
# hyperlinks = true
# post_processing = true
# persist = false
# action = "..."
# command = "..."
# binding = { key = "...", mods = "...", mode = "..." }
# mouse = { mods = "...", enabled = true }

# KEYBOARD section of Alacritty configuration

[keyboard]

# Define keyboard bindings here
# Example placeholder (actual bindings need to be defined based on user preference)
bindings = [
  { key =  "Minus",          mods =  "Command|Shift",              action =  "IncreaseFontSize"      },
  { key =  "Minus",          mods =  "Command",                    action =  "DecreaseFontSize"      },
#   { key =  "Yen",            chars  =  "\x5C"  },
#   { key =  "Yen", mods =  "Alt", chars  =  "\x5C"  },
  # alt + u が効くようにする(fot tmux)
#   { key =  "U"  , mods =  "Alt", chars  =  "\x1bu" },
  # for neovim keybinding
#   { key =  "Return",   mods =  "Shift",   chars =  "\x1b[13;2u" },
  # for tmux prefix
#   { key =  "Space", mods =  "Control", chars =  "\x00" },

  # ----- Alt Keys -----
  # { key =  "Key1",   mods =  "Alt",          chars =  "\x1B1" },
  # { key =  "Key2",   mods =  "Alt",          chars =  "\x1B2" },
  # { key =  "Key3",   mods =  "Alt",          chars =  "\x1B3" },
  # { key =  "Key4",   mods =  "Alt",          chars =  "\x1B4" },
  # { key =  "Key5",   mods =  "Alt",          chars =  "\x1B5" },
  # { key =  "Key6",   mods =  "Alt",          chars =  "\x1B6" },
  # { key =  "Key7",   mods =  "Alt",          chars =  "\x1B7" },
  # { key =  "Key8",   mods =  "Alt",          chars =  "\x1B8" },
  # { key =  "Key9",   mods =  "Alt",          chars =  "\x1B9" },
  # { key =  "Key0",   mods =  "Alt",          chars =  "\x1B0" },
  # { key =  "Minus",  mods =  "Alt",          chars =  "\x1B-" },
  # { key =  "Equals", mods =  "Alt",          chars =  "\x1B=" },
  # { key =  "A",      mods =  "Alt",          chars =  "\x1Ba" },
  # { key =  "B",      mods =  "Alt",          chars =  "\x1Bb" },
  # { key =  "C",      mods =  "Alt",          chars =  "\x1Bc" },
  # { key =  "D",      mods =  "Alt",          chars =  "\x1Bd" },
  # { key =  "E",      mods =  "Alt",          chars =  "\x1Be" },
  # { key =  "F",      mods =  "Alt",          chars =  "\x1Bf" },
  # { key =  "G",      mods =  "Alt",          chars =  "\x1Bg" },
  # { key =  "H",      mods =  "Alt",          chars =  "\x1Bh" },
  # { key =  "I",      mods =  "Alt",          chars =  "\x1Bi" },
  # { key =  "J",      mods =  "Alt",          chars =  "\x1Bj" },
  # { key =  "K",      mods =  "Alt",          chars =  "\x1Bk" },
  # { key =  "L",      mods =  "Alt",          chars =  "\x1Bl" },
  # { key =  "M",      mods =  "Alt",          chars =  "\x1Bm" },
  # { key =  "N",      mods =  "Alt",          chars =  "\x1Bn" },
  # { key =  "O",      mods =  "Alt",          chars =  "\x1Bo" },
  # { key =  "P",      mods =  "Alt",          chars =  "\x1Bp" },
  # { key =  "Q",      mods =  "Alt",          chars =  "\x1Bq" },
  # { key =  "R",      mods =  "Alt",          chars =  "\x1Br" },
  # { key =  "S",      mods =  "Alt",          chars =  "\x1Bs" },
  # { key =  "T",      mods =  "Alt",          chars =  "\x1Bt" },
  # { key =  "U",      mods =  "Alt",          chars =  "\x1Bu" },
  # { key =  "V",      mods =  "Alt",          chars =  "\x1Bv" },
  # { key =  "W",      mods =  "Alt",          chars =  "\x1Bw" },
  # { key =  "X",      mods =  "Alt",          chars =  "\x1Bx" },
  # { key =  "Y",      mods =  "Alt",          chars =  "\x1By" },
  # { key =  "Z",      mods =  "Alt",          chars =  "\x1Bz" },
  # { key =  "Key1",   mods =  "Alt|Shift",    chars =  "\x1B1" },
  # { key =  "Key2",   mods =  "Alt|Shift",    chars =  "\x1B2" },
  # { key =  "Key3",   mods =  "Alt|Shift",    chars =  "\x1B3" },
  # { key =  "Key4",   mods =  "Alt|Shift",    chars =  "\x1B4" },
  # { key =  "Key5",   mods =  "Alt|Shift",    chars =  "\x1B5" },
  # { key =  "Key6",   mods =  "Alt|Shift",    chars =  "\x1B6" },
  # { key =  "Key7",   mods =  "Alt|Shift",    chars =  "\x1B7" },
  # { key =  "Key8",   mods =  "Alt|Shift",    chars =  "\x1B8" },
  # { key =  "Key9",   mods =  "Alt|Shift",    chars =  "\x1B9" },
  # { key =  "Key0",   mods =  "Alt|Shift",    chars =  "\x1B0" },
  # { key =  "Minus",  mods =  "Alt|Shift",    chars =  "\x1B_" },
  # { key =  "Equals", mods =  "Alt|Shift",    chars =  "\x1B+" },
  # { key =  "A",      mods =  "Alt|Shift",    chars =  "\x1BA" },
  # { key =  "B",      mods =  "Alt|Shift",    chars =  "\x1BB" },
  # { key =  "C",      mods =  "Alt|Shift",    chars =  "\x1BC" },
  # { key =  "D",      mods =  "Alt|Shift",    chars =  "\x1BD" },
  # { key =  "E",      mods =  "Alt|Shift",    chars =  "\x1BE" },
  # { key =  "F",      mods =  "Alt|Shift",    chars =  "\x1BF" },
  # { key =  "G",      mods =  "Alt|Shift",    chars =  "\x1BG" },
  # { key =  "H",      mods =  "Alt|Shift",    chars =  "\x1BH" },
  # { key =  "I",      mods =  "Alt|Shift",    chars =  "\x1BI" },
  # { key =  "J",      mods =  "Alt|Shift",    chars =  "\x1BJ" },
  # { key =  "K",      mods =  "Alt|Shift",    chars =  "\x1BK" },
  # { key =  "L",      mods =  "Alt|Shift",    chars =  "\x1BL" },
  # { key =  "M",      mods =  "Alt|Shift",    chars =  "\x1BM" },
  # { key =  "N",      mods =  "Alt|Shift",    chars =  "\x1BN" },
  # { key =  "O",      mods =  "Alt|Shift",    chars =  "\x1BO" },
  # { key =  "P",      mods =  "Alt|Shift",    chars =  "\x1BP" },
  # { key =  "Q",      mods =  "Alt|Shift",    chars =  "\x1BQ" },
  # { key =  "R",      mods =  "Alt|Shift",    chars =  "\x1BR" },
  # { key =  "S",      mods =  "Alt|Shift",    chars =  "\x1BS" },
  # { key =  "T",      mods =  "Alt|Shift",    chars =  "\x1BT" },
  # { key =  "U",      mods =  "Alt|Shift",    chars =  "\x1BU" },
  # { key =  "V",      mods =  "Alt|Shift",    chars =  "\x1BV" },
  # { key =  "W",      mods =  "Alt|Shift",    chars =  "\x1BW" },
  # { key =  "X",      mods =  "Alt|Shift",    chars =  "\x1BX" },
  # { key =  "Y",      mods =  "Alt|Shift",    chars =  "\x1BY" },
  # { key =  "Z",      mods =  "Alt|Shift",    chars =  "\x1BZ" }
]
