# Import additional configuration files
import = [
  "~/.config/alacritty/themes/nord.toml",
  "~/.config/alacritty/fonts/CaskaydiaMono.toml",
]

shell = { program = "tmux", args = ["new-session"] }

[window]
padding = { x = 16, y = 14 } # Default: x = 0, y = 0
decorations = "None"         # Default: "Full"
dimensions.columns = 90
dimensions.lines = 25

[scrolling]
history = 100_000 # Default: 10000

[font]
size = 9.5                # Default: 11.25
offset = { x = 0, y = 1 } # Default: x = 0, y = 0

[terminal]
# Controls the OSC 52 behavior for clipboard interactions
osc52 = "CopyPaste" # Default: "OnlyCopy"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
